modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "mystcraftages"
version = "${version}"
displayName = "Mystcraft: Ages"
authors = "naomieow"
description = '''
Mystcraft: Ages is a modern rewrite and reimagining of the original "Mystcraft" mod.
'''
#logoFile = ""

[[dependencies.mystcraftages]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mystcraftages]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mystcraftages]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"